name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: python-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        id: docker_build   # ⬅️ INI SAJA YANG DITAMBAHKAN
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: |
            irwan34/python-app:latest
            irwan34/python-app:1.0.0
            irwan34/python-app:${{ github.sha }}

      - name: Show image digest
        run: |
          echo "================================"
          echo "Docker Image Digest:"
          echo "${{ steps.docker_build.outputs.digest }}"
          echo "================================"
      - name: Update GitOps repo with new image digest
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/irwanmaul34/project-devops-gitops.git
          cd gitops

          sed -i "s|image: .*|image: irwan34/python-app@${{ steps.docker_build.outputs.digest }}|" production/deployment.yaml

          git config user.name "ci-bot"
          git config user.email "ci@github.com"

          git status
          git commit -am "Update myapp image to ${{ steps.docker_build.outputs.digest }}"
          git push origin main

