name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  FRONTEND_IMAGE: irwan34/frontend-service
  API_IMAGE: irwan34/api-service


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        id: build_api
        uses: docker/build-push-action@v5
        with:
          context: ./api-service
          push: true
          tags: |
            ${{ env.API_IMAGE }}:latest
            ${{ env.API_IMAGE }}:${{ github.sha }}
          
      - name: Build and push Frontend image
        id: build_frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-service
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}



      - name: Show image digest API
        run: |
          echo "================================"
          echo "Docker Image Digest:"
          echo "${{ steps.build_frontend.outputs.digest }}"
          echo "================================"

      - name: Show image digest API
        run: |
          echo "================================"
          echo "Docker Image Digest:"
          echo "${{ steps.build_api.outputs.digest }}"
          echo "================================"
          
      - name: Update Production GitOps
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/irwanmaul34/project-devops-gitops.git
          cd project-devops-gitops
      
          sed -i "s|image: .*frontend-service.*|image: ${{ env.FRONTEND_IMAGE }}@${{ steps.build_frontend.outputs.digest }}|" production/frontend-deployment.yaml
      
          sed -i "s|image: .*api-service.*|image: ${{ env.API_IMAGE }}@${{ steps.build_api.outputs.digest }}|" production/api-deployment.yaml
      
          git config user.name "ci-bot"
          git config user.email "ci@github.com"
      
          git add .
          git commit -m "Update production images"
          git push origin main


      - name: Update Staging GitOps
        run: |
          rm -rf gitops
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/irwanmaul34/project-devops-gitops.git gitops
          cd gitops/staging
      
          sed -i "s|image: .*frontend-service.*|image: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}|" frontend-deployment.yaml
      
          sed -i "s|image: .*api-service.*|image: ${{ env.API_IMAGE }}:${{ github.sha }}|" api-deployment.yaml
      
          git config user.email "ci@github.com"
          git config user.name "github-actions"
      
          git add .
          git commit -m "chore(staging): update images to ${{ github.sha }}"
          git push origin main


